### ISSUE TITLE
mongoose.tests.test_parser.test_parse_string_literal is failing

### ISSUE THREAD

**Issue by christopher-haueter** [etanzapinsky/mongoose#7]
The frontend is considering "hello" to be of STAT_LIST vtype, not STRING_VALUE.

``` ======================================================================
ERROR: mongoose.tests.test_parser.test_parse_string_literal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chris/.virtualenvs/plt/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/chris/Dropbox/2013/plt/lang/mongoose/tests/test_parser.py", line 20, in test_parse_string_literal
    eq_(parser.parse(src), node)
  File "/Users/chris/.virtualenvs/plt/lib/python2.7/site-packages/nose/tools/trivial.py", line 28, in eq_
    if not a == b:
  File "/Users/chris/Dropbox/2013/plt/lang/mongoose/parser/tree.py", line 21, in __eq__
    raise TypeError, "'{}' is not comparable with '{}'".format(self.vtype, other.vtype)
TypeError: 'STAT_LIST' is not comparable with 'STRING_VALUE'
-------------------- >> begin captured stdout << ---------------------
LexToken(VSTRING,'"hello"',1,0)
Syntax error in input!
[Node: None STAT_LIST, None, None, [None, None]]
LexToken(VSTRING,'"hello"',1,0)
Syntax error in input!

--------------------- >> end captured stdout << ----------------------
```

**Comment by mnrubin** [comment]
I'll take a look later, but be aware that there will be a hierarchy of nodes and the leaf will be a  string value (editing the "testfile" and running the parser with it as a commandline parameter will show you what the tree looks like for any statement)

**Comment by mnrubin** [comment]
Is this bug still occurring @chrishaum ? What is the code that is causing it?

**Comment by christopher-haueter** [comment]
The test seems to have been removed by @captainbox22 from the test suite. (see tests/test_parser.py)

**Comment by mnrubin** [comment]
shall we resolve this issue?

**Comment by boxu9** [comment]
was this through a bad push?

**Comment by christopher-haueter** [comment]
tests rot, it happens. No problem, IMO
